### PR TITLE
Fix issues in MQTT Adapter

### PR DESCRIPTION
**Pull request by abhijitnathwani**
This PR fixes the issues in MQTT Adapter that were causing failure to build
- incorrect json key in header file
- changed mqtt port in config file from string to int

### CODE REVIEW

**Comment by dipannita08** [comment]
The fix should be made in the following way:
  - [Update Line 130 mqtt_cpp.cpp](https://github.com/Azure/iot-plug-and-play-bridge/blob/5a5d5972b30bb060898e362f60bb89157372711d/pnpbridge/src/adapters/src/mqtt_pnp/mqtt_pnp.cpp#L130) from:
`const char* mqttConfigId = json_object_get_string(AdapterComponentConfig, PNP_CONFIG_ADAPTER_MQTT_SUPPORTED_CONFIG);`
to:
`const char* mqttConfigId = json_object_get_string(AdapterComponentConfig, PNP_CONFIG_ADAPTER_MQTT_IDENTITY);`
 - The config file is just a sample so generally is expected to be updated whenever running the bridge with interface components that require specific adapters. Changes in this file don't need to be merged generally. But the change you have made in the config.json file is good to merge, so lets keep this.
 - Please re-target your branch to merge into Azure/iot-plug-and-play-bridge:master rather than Azure:master

**Review by dipannita08 — CHANGES_REQUESTED** [review]
The fix should be made in the following way:

 - Update [Line 130 mqtt_cpp.cpp](https://github.com/Azure/iot-plug-and-play-bridge/blob/5a5d5972b30bb060898e362f60bb89157372711d/pnpbridge/src/adapters/src/mqtt_pnp/mqtt_pnp.cpp#L130) from:
`const char* mqttConfigId = json_object_get_string(AdapterComponentConfig, PNP_CONFIG_ADAPTER_MQTT_SUPPORTED_CONFIG);`
to:
`const char* mqttConfigId = json_object_get_string(AdapterComponentConfig, PNP_CONFIG_ADAPTER_MQTT_IDENTITY);`
 - The config file is just a sample so generally is expected to be updated whenever running the bridge with interface components that require specific adapters. Changes in this file don't need to be merged generally. But the change you have made in the config.json file is good to merge, so lets keep this.
 - Please re-target your branch to merge into Azure/iot-plug-and-play-bridge:master rather than Azure:master

**Comment by abhijitnathwani** [comment]
Hi @dipannita08 
I have added the changes as sugggested. For point #3 , re-targeting to `Azure/iot-plug-and-play-bridge:master` I can't find this branch in the dropdown.

image

**Comment by dipannita08** [comment]
I've taken care of the fix I recommended [here.](https://github.com/Azure/iot-plug-and-play-bridge/pull/42/commits/b1560bcfa396b367db2997268169bd3054428eb5)

**Comment by abhijitnathwani** [comment]
Alright thanks @dipannita08

**Pull request closed without merging**
